myblog/blog/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "blog"

urlpatterns = [
    path('home', views.BlogList, name='home'),  
    path('blogposts/<slug:slug>/', views.PostList, name='post_list'),
    path('post-create/', views.post_create, name='post_create'),
    path('post/<slug:slug>/', views.PostDetail, name='post_detail'),
    path('post-update/<int:id>/', views.post_update, name='post_update'),
    path('post/<slug:postid>/preference/<userpreference>/', views.postpreference, name='postpreference'),
] 

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("blog.urls")),
    path('', include('django.contrib.auth.urls')),
    path('password-reset/', include('password_reset.urls')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
]

myblog/userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
   
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
   # path('edit/<int:id>/', views.profile_edit, name='edit'),
]

myblog/templates/base.html
<!DOCTYPE html>
<html>

    <head>
        <title>FT&AD HSE x Sber Masters Program</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
            crossorigin="anonymous" />
    </head>

    <body>
        <style>
            body {
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;
        }
        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }
        .btn-danger {
            color: #fff;
            background-color: #778899;
            border-color: #778899;
        }
        .masthead {
            background: #778899;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px;
        }
    </style>

        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'blog:home' %}">FT&AD HSE x Sber Master Students Community</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="https://www.hse.ru/ma/fintech">About</a>
                        </li>

                        <li  class="nav-item">
                            <a  class="nav-link text-black font-weight-bold" href="{% url 'blog:post_create' %}">New post </a>
                           </li>
                        <!-- <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Policy</a>
                        </li> -->
                        <!-- <li class="nav-item text-black">
                            <a class="nav-link text-black font-weight-bold" href="#">Contact</a>
                        </li> -->
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}
        <!-- Content Goes here -->
        {% endblock content %}
        <!-- Footer -->
        <footer class="py-3 bg-grey">
            <p class="m-0 text-dark text-center ">Thanks to Django Central and @stacklens for templates and tutorials</p>
        </footer>
    </body>
</html>

myblog/templates/blogsindex.html
{% extends "base.html" %} 
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-2 mt-1 text-white"> Welcome to Financial Technologies and 
                        Data Analysis Master program Community Page </h3>
                    <!-- <p class="text-light">We Love Django As much as you do..! &nbsp </p>-->                    
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for blog in home %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ blog.Name }}</h2>                  
                    <a href="{% url 'blog:post_list' blog.Slug  %}" class="btn btn-link">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

myblog/templates/create.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %}  {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="Title">Title</label>
                    <input type="text" 
                           class="form-control" 
                           id="Title" 
                           name="Title"
                    >
                </div>
                
                <div class="form-group">
                    <label for="blog">Choose blog</label>
                    <select class="form-control col-3" id="blog" name="blog">
                        {% for blog in columns %}
                            <option value="{{ blog.id }}">{{ blog }}</option>
                        {% endfor %}
                    </select>
                </div> 

                 <div class="form-group">
                    <label for="tags">Tags</label>
                    <input type="text" 
                           class="form-control col-3" 
                           id="tags" 
                           name="tags"
                    >
                </div>

                <div class="form-group">
                    <label for="Content">Content</label>
                    <textarea type="text" 
                              class="form-control" 
                              id="Content" 
                              name="Content" 
                              rows="12"
                    ></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

myblog/templates/edit.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 用户信息 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">用户名: {{ user.username }}</div>
            <br>
            {% if profile.avatar %}
                <div class="col-md-4">头像</div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
            {% else %}
                <h5 class="col-md-4">暂无头像</h5>
            {% endif %}
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <!-- avatar -->
                <div class="form-group col-md-4">
                    <label for="avatar">上传头像</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <!-- phone -->
                <div class="form-group col-md-4">
                    <label for="phone">电话</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>
                <!-- bio -->
                <div class="form-group col-md-4">
                    <label for="bio">简介</label>
                    <!-- 文本区域 -->
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

myblog/templates/index.html
{% extends "base.html" %} 
{% load thumbnail %}
{% block content %}
<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }
    
    .head_text {
        color: white;
    }
    
    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-2 mt-1 text-white"> Here are  {{ blog.Name }}  related posts</h3>
                    <!-- <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p> -->
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
            {% for post in post_list %}
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">{{ post.Title }}</h2>
                    <p class="card-text text-muted h6">{{ post.Author }} | {{ post.Date}} </p>
                    <p class="card-text">{{post.Content|slice:":200"| safe }}</p>
                    {% if post.Image %}
                        {% thumbnail post.Image "300x400" crop="center" as im %}
                        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                        {% endthumbnail %}
                    {% endif %}
                    
                    <!--  Label -->
                    
                    
                </div>
                <span >
                        {% for tag in post.tags.all %}
                         
                         <a href="{% url 'blog:post_list' post.blog_id %}?tag={{ tag }}" 
                                class="badge badge-secondary"
                        >
                        {{ tag }}
                        </a>
                        {% endfor %}
                    </span>
                 <a href="{% url 'blog:post_detail' post.Slug  %}" class="btn btn-link">Read More &rarr;</a> 
            </div>
            {% endfor %}
        </div>
        {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}
    </div>
</div>
{%endblock%}

myblog/templates/login.html
{% extends "base.html" %} 
<!-- {% load staticfiles %} -->
{% block title %} Log in page {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <h5>Have no profile yet?</h5>
            <h5><a href='{% url "userprofile:register" %}'>Register</a></h5>
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <!-- 账号 -->
                <div class="form-group col-md-4">
                    <label for="username">Enter username</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <!-- 密码 -->
                <div class="form-group col-md-4">
                    <label for="password">Enter password</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <!-- 提交按钮 -->
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <br>
            <h5>Forgot password?</h5> 
            <h5>Recover it <a href='{% url "password_reset_recover" %}' here> here</a></h5>
        </div>
    </div>
</div>
{% endblock content %}

myblog/templates/post_detail.html
{% extends 'base.html' %} {% block content %}
{% load thumbnail %}
{% load crispy_forms_tags %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">    
        <a href="{% url "blog:post_list" post.blog.id %}">Back to blog's posts</a>     

        <h1>{% block title %} {{ post.Title }}  {% endblock title %}            
        </h1>
        
         <p class=" text">{{ post.Author }}  {{ post.Date }} 
           {% if user == post.Author %}
            <a href="{% url "blog:post_update" post.id %}">
               Edit
           </a>
            {% endif %}
          </p> 
        <p class="card-text ">{{ post.Content |safe}}</p>
        {% if post.Image %}
        {% thumbnail post.Image "300x400" crop="center" as im %}
        <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
        {% endif %}

        
      </div>
    <div>
      <a href="#" onClick="document.getElementById('likebutton').submit()">Like </a> {{post.likes}} 
        <a href="#" onClick="document.getElementById('dislikebutton').submit()">Dislike</a> {{post.dislikes}}
        <form id="likebutton" method="POST" action="/post/{{post.id}}/preference/1/">
        {% csrf_token %}
        <input type="hidden">
        </form>
    
        <form id="dislikebutton" method="POST" action="/post/{{post.id}}/preference/2/">
        {% csrf_token %}
        <input type="hidden">
      </form>
    </div>
    </div>
    {% block sidebar %} {% include 'sidebar.html' %} {% endblock sidebar %}

    <div class="col-md-8 card mb-4 mt-3 ">
      <div class="card-body">
        
        <h2>{{ comments.count }} comments</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body| safe | linebreaks  }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
      </div>
    </div>
  
</div>

{% endblock content %}

myblog/templates/register.html
{% extends "base.html" %} 
<!-- {% load staticfiles %} -->
{% block title %} Register {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group col-md-4">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email">
                </div>
                <div class="form-group col-md-4">
                    <label for="password">Enter password</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <div class="form-group col-md-4">
                    <label for="password2">Enter password again</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <button type="submit" class="btn btn-primary">Sign up</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

myblog/templates/sidebar.html
{% block sidebar %}

<style>
        .card{
            box-shadow: 0 16px 48px #E3E7EB;
        }
       
</style>

<!-- Sidebar Widgets Column -->
<div class="col-md-4 float-right ">
<div class="card my-4">
        <h5 class="card-header">About Us</h5>
    <div class="card-body">
        <p class="card-text"> This programme is offered by HSE in collaboration with Sberbank. Its goal is to train future professionals to analyse different data forms (numerical and text data, graphs and images), develop models for machine learning and predictable analytics and, equally important, to create business value using mathematical models. </p>
        <a href="https://www.hse.ru/en/ma/fintech/"
           class="btn btn-link">Check more</a>
    </div>
</div>
</div>

{% endblock sidebar %}

myblog/templates/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="Title">Post title</label>
                    <textarea type="text" class="form-control" id="Title" name="Title" rows="1">{{ post.Title }}</textarea>
                    <!-- <input type="text" class="form-control" id="Title" name="Title" value="{{ article.Title }}"> -->
                </div>    

                <div class="form-group">
                     <label for="tags">Tags</label>
                     <input type="text" class="form-control col-3" id="tags" name="tags"
                        value="{{ tags }}">
                </div>

                <!-- 文章正文 -->
                <div class="form-group">
                    <label for="Content">Enter text</label>
                    <textarea type="text" class="form-control" id="Content" name="Content" rows="12">{{ post.Content }}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}